### PR TITLE
Update README.md

### LINKED ISSUE #6: Why does it need to be in application
Hi, I don't understand why you need to add :phoenix_swoosh into applications it does not have a start function.

### PR DESCRIPTION
**Pull request by princemaple**
phoenix_swoosh is not an application

@stevedomin 

close #6

### CODE REVIEW

**Comment by princemaple** [comment]
I actually don't know if it's a good move. And I don't use releases. 🤷‍

**Comment by princemaple** [comment]
I guess it does fall into the very last category? https://www.amberbit.com/blog/2016/5/10/creating-elixir-libraries-as-otp-applications/#comment-2677186959

**Comment by stevedomin** [comment]
@princemaple You think it's not relevant anymore?

**Comment by princemaple** [comment]
I think I didn't understand everything clearly when I sent this PR. I can't
get back to it anytime soon so I'd like to close it for now, so to avoid
confusion. :)

I think in 1.4 you don't need to add anything to applications list.

**Comment by princemaple** [comment]
If using extra applications

**Comment by stevedomin** [comment]
Ok. I'll have a look at that.

**Pull request closed without merging**
